tool.ragdollfollower.name=Ragdoll Follower
tool.ragdollfollower.desc=Make a ragdoll follow another ragdoll
tool.ragdollfollower.right=View controller entity data
tool.ragdollfollower.left=Select the controller entity
tool.ragdollfollower.left_1=Select the follower entity
tool.ragdollfollower.reload=Remove ragdoll follower constraint

tool.ragdollfollower.general=Select an entity from the explorer to view its data and modify it

tool.ragdollfollower.entities=Entities
tool.ragdollfollower.bones=Bones
tool.ragdollfollower.bones.constraint=Constraint
tool.ragdollfollower.bones.update=Update bones
tool.ragdollfollower.settings=Settings